In [4]:
!pip install nltk
!pip install numpy
!pip install pandas

    100% |████████████████████████████████| 1.2MB 561kB/s ta 0:00:011
  Running setup.py bdist_wheel for nltk ... done
  Stored in directory: /home/jovyan/.cache/pip/wheels/18/9c/1f/276bc3f421614062468cb1c9d695e6086d0c73d67ea363c501
Successfully built nltk


In [92]:
import nltk as nltk
import numpy as np
import pandas as pd
import collections as coll

from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.utils.multiclass import unique_labels

def string_to_ngrams(s, n):
    # text = str(s).decode('utf-8').lower()
    text = str(s).lower()
    text = text.replace(' ', '')
    ngrams = nltk.ngrams([c for c in text], n)
    return [''.join(g) for g in ngrams]

class NaiveBayesClassifier(BaseEstimator, ClassifierMixin):  
    def __init__(self,
                 n_gram=1,
                 multimap=True,
                 count_threshold=0,
                 use_uniform_prior=False,
                 laplace_smoothing=1.):
        self.n_gram = n_gram
        self.multimap = multimap
        self.count_threshold = count_threshold
        self.use_uniform_prior = use_uniform_prior
        self.laplace_smoothing = laplace_smoothing

    def fit(self, X=None, y=None):
        W = pd.DataFrame({'X': [X], 'y': [y]})
        
        # Count features
        counts = {}
        for (xx, yy) in zip(X, y):
            category = np.zeros(5)
            category[yy] = 1
            ngrams = string_to_ngrams(xx, self.n_gram)
            if not self.multimap:
                ngrams = list(set(ngrams))
            for ngram in ngrams:
                if ngram in counts:
                    counts[ngram] = counts[ngram] + category
                else:
                    counts[ngram] = category
        counts = pd.DataFrame(counts).transpose()

        # Filter low counts
        keep = counts.apply(lambda row: sum(row) >= self.count_threshold, axis = 1)
        counts = counts[keep == 1]
        
        # Apply Laplace smoothing by adding a letter
        counts[counts.columns[-5:]] += self.laplace_smoothing
        
        # Count the # of n-grams observed in each language.
        class_counts = np.array(counts[counts.columns[-5:]].apply(lambda x: np.sum(x) * 1., axis = 0).values)
        
        # Define P(Y = y) as the proportion of n-grams observed in each language.
        if self.use_uniform_prior:
            class_priors = np.full(5, .1/5)
        else:
            class_priors = class_counts / np.sum(class_counts)
            
        ## self.likelihood_ = counts.div(class_counts)
        self.likelihood_ = np.log(counts.div(class_counts))
        self.counts_ = counts
        ## self.class_priors_ = class_priors
        self.class_priors_ = np.log(class_priors)
        
        return self

    def predict(self, X):
        predictions = []

        for obs in X:
            levels = string_to_ngrams(obs, n = self.n_gram)
            
            joint_likelihood = np.full(5, 1.0)
            ## joint_likelihood = np.full(5, 0.)
            
            # Calculate joint probability
            for level in levels:
                if not level in self.likelihood_.index:
                    continue
                    
                # Calculate likelihood for X
                likelihood = self.likelihood_[self.likelihood_.index == level][:1].reset_index().values
                likelihood = np.array(np.delete(likelihood, 0).astype(float))
                
                ## joint_likelihood = np.multiply(joint_likelihood, likelihood)
                joint_likelihood = joint_likelihood + likelihood
                
            # Calculate joint likelihood * class prior
            ## prop_posterior = np.multiply(joint_likelihood, self.class_priors_)
            prop_posterior = joint_likelihood + self.class_priors_

            # Calculate posterior probability
            posterior = prop_posterior #/ np.sum(prop_posterior)
            prediction = np.argmax(posterior)
            
            predictions = predictions + [prediction]
        
        return predictions
    
    
    def classify(self, inputs):
        return
 

In [93]:
# from sklearn.pipeline import Pipeline, FeatureUnion

X_train = pd.read_csv("data/train_set_x.csv")['Text'].values
Y_train = pd.read_csv("data/train_set_y.csv")['Category'].values
X_test  = pd.read_csv("data/test_set_x.csv")['Text'].values
nbayes = NaiveBayesClassifier()
nbayes.set_params(n_gram=1,
                  multimap=True,
                  count_threshold=25,
                  use_uniform_prior=False,
                  laplace_smoothing=10.0)
nbayes.fit(X_train, Y_train)
nbayes.likelihood_


0          1          2          3          4
0   -6.654122  -6.384704  -6.371843  -6.502534  -9.365380
1   -6.377911  -6.131082  -6.510420  -6.349567  -9.463019
2   -6.493825  -6.298926  -6.767197  -6.723717  -9.600220
3   -6.905085  -6.761981  -7.134177  -7.169426  -9.794376
4   -7.274748  -6.984214  -7.404901  -7.789680 -10.236209
5   -7.112115  -6.610124  -7.259857  -7.504370  -9.759285
6   -7.457988  -6.670123  -7.434524  -7.393207 -10.236209
7   -7.547255  -6.413297  -7.501418  -7.764717 -10.353992
8   -7.615818  -7.107474  -7.559687  -8.160217 -10.418530
9   -7.963319  -6.706963  -7.452328  -7.898029 -10.487523
a   -2.211921  -2.619134  -2.238511  -2.665011  -2.473353
b   -4.037150  -4.423137  -4.313830  -3.935473  -4.059649
c   -3.820184  -3.390167  -3.277092  -3.257607  -3.307399
d   -3.392050  -3.561555  -3.264732  -3.064531  -3.517196
e   -2.384520  -2.035875  -2.070703  -1.973825  -2.531547
f   -6.191544  -4.504860  -4.897719  -4.294945  -6.558503
g   -6.181502  -4.773149  -4.209731  -3.758926  -4.510447
h   -4.116577  -4.440494  -4.136607  -2.851689  -4.655431
i   -2.891890  -2.704083  -2.921920  -2.468436  -2.515599
j   -3.680520  -4.251138  -5.094542  -5.435525  -3.645602
k   -3.246615  -6.230496  -5.950842  -4.297105  -3.642099
l   -3.352956  -3.139286  -3.118256  -3.198637  -4.131912
m   -3.020959  -3.530918  -3.510986  -3.522050  -3.331960
n   -2.933299  -2.760280  -2.736345  -2.437028  -3.053857
o   -2.458340  -2.805331  -2.424028  -3.423617  -2.721439
p   -3.523788  -3.507671  -3.556713  -4.473972  -3.649654
q   -9.460570  -4.479941  -4.400671  -8.556570 -10.353992
r   -3.306319  -2.824319  -2.854490  -2.857424  -3.429256
s   -3.003256  -2.579035  -2.667435  -2.777645  -3.245032
t   -2.923819  -2.758829  -3.018735  -2.827553  -3.259549
..        ...        ...        ...        ...        ...
�  -10.787441 -11.152793  -9.907734 -11.349778 -10.823995
�  -10.867484 -12.299607  -6.826251 -10.872854 -10.418530
�  -10.954495 -11.984526 -10.742195 -11.937565 -10.823995
�   -8.469588  -9.925563  -5.833487 -11.937565  -5.055362
�   -6.801310  -7.758679 -11.053975 -10.433488 -10.641674
�  -11.049805 -12.299607 -11.509450 -11.937565 -10.823995
�  -11.049805 -11.452309 -11.723024  -6.026768 -10.641674
�  -11.049805 -12.194247 -11.548671 -11.937565 -10.823995
�  -11.049805 -10.841854  -9.008645 -11.937565 -10.823995
�  -11.049805  -8.675760 -10.450059 -11.937565 -10.082058
�   -5.934210 -12.040096  -7.169147 -11.937565  -6.761830
�  -11.049805  -8.140724 -11.589493 -10.433488  -7.853581
�  -10.954495 -11.957858  -9.923360  -5.357064  -4.577307
�   -5.896514  -6.184860  -9.387649 -11.937565 -10.641674
�   -5.063102 -12.504402 -11.632053 -11.937565 -10.823995
�  -11.049805  -6.185188  -6.050028 -10.179707 -10.823995
�  -10.644340  -8.721246  -4.898392  -9.576711 -10.130848
�   -3.865859  -3.836808  -4.129554  -4.382497  -5.047892
�   -4.912078 -12.822855  -8.935664 -10.774414  -3.509043
�   -4.312127  -9.978673  -8.881443 -11.755243  -3.256391
�  -11.049805 -12.504402 -11.509450 -11.937565 -10.823995
�  -10.954495 -13.110537  -9.342597 -11.937565 -10.823995
�  -11.049805 -12.098936 -11.877175 -11.937565 -10.823995
�  -11.049805 -11.881872 -10.707104 -11.937565 -10.823995
�  -11.049805 -12.956387 -11.271039 -11.937565 -10.823995
�  -11.049805 -12.550922 -11.471710 -11.937565 -10.823995
�   -9.401147  -5.403138  -8.203691  -6.724805  -5.762667
�  -11.049805 -12.011925 -11.934333 -11.937565 -10.823995
�  -11.049805  -6.177277  -9.410960 -10.179707 -10.823995
�  -11.049805  -6.652069  -9.783940 -11.937565 -10.823995

[114 rows x 5 columns]

In [94]:
len(nbayes.likelihood_)
len(X_test)

len(X_train)

276517

In [95]:
## GENERALIZED CONFUSION MATRIX

true_x = X_train[250000:250100]
true_y = Y_train[250000:250100]
pred_y = nbayes.predict(true_x)

loss = np.full((5,5), 1.0)
for i in range(len(pred_y)):
    loss[pred_y[i], true_y[i]] += 1
    
TPR = loss.trace() / loss.sum()
FNR = 1 - TPR

print(loss)
print(TPR)
print(FNR)
print(accuracy_score(pred_y, true_y))
print(precision_score(pred_y, true_y, average = 'macro'))

[[  8.   1.   2.   1.   1.]
 [  1.  50.   5.   2.   1.]
 [  1.   4.  14.   3.   1.]
 [  1.   2.   3.   8.   1.]
 [  1.   1.   1.   1.  11.]]
0.728
0.272
0.86
0.854905660377


In [137]:
#### RANDOM TRAIN-TEST SPLIT

import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split

import random

xx = X_train
yy = Y_train

param_grid = [
  {
        'n_gram': [1, 2, 3],
        'laplace_smoothing': [1., 10.],
        'cv_count_threshold': [0., 10., 25.]
  }
 ]

scoring = {'acc':        'accuracy',
           'prec_macro': 'precision_macro',
           'rec_micro':  'recall_macro'}

def train_test_split_model(model, xxx, yyy, test_size=0.004):
    xxx_train, xxx_test, yyy_train, yyy_test = train_test_split(xxx, yyy, test_size=test_size)
    model.fit(xxx_train, yyy_train)
    yyy_pred = model.predict(xxx_test)
    test_accuracy = accuracy_score(yyy_test, yyy_pred)
    test_precision = precision_score(yyy_test, yyy_pred, average = 'macro')
    test_recall = recall_score(yyy_test, yyy_pred, average = 'macro')
    number_of_features = len(model.likelihood_)
    return({
            'n': model.n_gram,
            'lam': model.laplace_smoothing,
            'c': model.count_threshold,
            'number_of_features': number_of_features,
            'test_accuracy': test_accuracy,
            'test_precision': test_precision,
            'test_recall': test_recall,
            'test_average': np.mean([test_accuracy, test_precision, test_recall])
           })

tts_scores = {}

In [138]:
# print(train_test_split_model(NaiveBayesClassifier(n_gram=1, laplace_smoothing=10., count_threshold=25), xx, yy))

In [139]:
#for i_n in [1, 2, 3]:
#    k = "n={},lam={},c={}".format(i_n, 1., 0)
#    v = train_test_split_model(NaiveBayesClassifier(n_gram=i_n), xx, yy)
#    tts_scores[k] = v

In [140]:
#for i_lam in [1., 25., 50.]:
#    k = "n={},lam={},c={}".format(1, i_lam, 0)
#    v = train_test_split_model(NaiveBayesClassifier(laplace_smoothing=i_lam), xx, yy)
#    tts_scores[k] = v

In [141]:
#for i_c in [1, 25, 50]:
#    k = "n={},lam={},c={}".format(1, 1., i_c)
#    v = train_test_split_model(NaiveBayesClassifier(count_threshold=i_c), xx, yy)
#    tts_scores[k] = v

In [142]:
tts_superscore2 = {}

for i_n in [1, 2, 3]:
    for i_lam in [1., 25., 50.]:
        for i_c in [1, 25, 50]:
            k = "n={},lam={},c={}".format(i_n, i_lam, i_c)
            print(k)
            v = train_test_split_model(NaiveBayesClassifier(n_gram=i_n, laplace_smoothing=i_lam, count_threshold=i_c), xx, yy)
            tts_superscore2[k] = v

n=1,lam=1.0,c=1
n=1,lam=1.0,c=25
n=1,lam=1.0,c=50
n=1,lam=25.0,c=1
n=1,lam=25.0,c=25
n=1,lam=25.0,c=50
n=1,lam=50.0,c=1
n=1,lam=50.0,c=25
n=1,lam=50.0,c=50
n=2,lam=1.0,c=1
n=2,lam=1.0,c=25
n=2,lam=1.0,c=50
n=2,lam=25.0,c=1
n=2,lam=25.0,c=25
n=2,lam=25.0,c=50
n=2,lam=50.0,c=1
n=2,lam=50.0,c=25
n=2,lam=50.0,c=50
n=3,lam=1.0,c=1
n=3,lam=1.0,c=25
n=3,lam=1.0,c=50
n=3,lam=25.0,c=1
n=3,lam=25.0,c=25
n=3,lam=25.0,c=50
n=3,lam=50.0,c=1
n=3,lam=50.0,c=25
n=3,lam=50.0,c=50


In [143]:
#### K FOLD IS TOO SLOW

#import numpy as np
#from sklearn.model_selection import KFold
#from sklearn.cross_validation import cross_val_score
#from sklearn.model_selection import cross_validate
#from sklearn.metrics import accuracy_score, precision_score, recall_score

#import random

#xx = X_train[:1000]
#yy = Y_train[:1000]

#scoring = {'acc': 'accuracy',
#           'prec_macro': 'precision_macro',
#           'rec_micro': 'recall_macro'}

#print("cv_n_gram")
#cv_n_gram = None
#for i in range(1, 3):
##    print(i)
#    a = cross_validate(NaiveBayesClassifier(n_gram=i),
#                       xx,
#                       yy,
#                       fit_params={},
#                       scoring=scoring,
#                       cv=2,
#                       return_train_score=True)
#    a_mean = pd.DataFrame(a).mean(axis=0)
#    cv_n_gram = pd.concat((cv_n_gram,
#                           a_mean.rename("n_gram={}".format(i))), axis=1)

#print("cv_laplace_smoothing")
#cv_laplace_smoothing = None
#for i in [1., 5., 10.]:
#    print(i)
#    a = cross_validate(NaiveBayesClassifier(laplace_smoothing=i),
#                       xx,
#                       yy,
#                       fit_params={},
#                       scoring=scoring,
#                       cv=2,
#                       return_train_score=True)
#    a_mean = pd.DataFrame(a).mean(axis=0)
#    cv_laplace_smoothing = pd.concat((cv_laplace_smoothing,
#                                      a_mean.rename("laplace_smoothing={}".format(i))), axis=1)
    
#print("cv_count_threshold")
#cv_count_threshold = None
#for i in [0., 10., 25.]:
#    print(i)
#    a = cross_validate(NaiveBayesClassifier(count_threshold=i),
#                       xx,
#                       yy,
#                       fit_params={},
#                       scoring=scoring,
#                       cv=2,
#                       return_train_score=True)
#    a_mean = pd.DataFrame(a).mean(axis=0)
#    cv_count_threshold = pd.concat((cv_count_threshold,
#                                    a_mean.rename("count_threshold={}".format(i))), axis=1)

In [146]:
pd.DataFrame(tts_superscore2).transpose()

c   lam    n  number_of_features  test_accuracy  \
n=1,lam=1.0,c=1     1.0   1.0  1.0               131.0       0.878049   
n=1,lam=1.0,c=25   25.0   1.0  1.0               114.0       0.873532   
n=1,lam=1.0,c=50   50.0   1.0  1.0               106.0       0.865402   
n=1,lam=25.0,c=1    1.0  25.0  1.0               131.0       0.854562   
n=1,lam=25.0,c=25  25.0  25.0  1.0               114.0       0.841915   
n=1,lam=25.0,c=50  50.0  25.0  1.0               106.0       0.853659   
n=1,lam=50.0,c=1    1.0  50.0  1.0               131.0       0.859079   
n=1,lam=50.0,c=25  25.0  50.0  1.0               114.0       0.852755   
n=1,lam=50.0,c=50  50.0  50.0  1.0               106.0       0.865402   
n=2,lam=1.0,c=1     1.0   1.0  2.0              4094.0       0.953026   
n=2,lam=1.0,c=25   25.0   1.0  2.0              2309.0       0.933153   
n=2,lam=1.0,c=50   50.0   1.0  2.0              2003.0       0.942186   
n=2,lam=25.0,c=1    1.0  25.0  2.0              4094.0       0.915989   
n=2,lam=25.0,c=25  25.0  25.0  2.0              2309.0       0.938573   
n=2,lam=25.0,c=50  50.0  25.0  2.0              2003.0       0.942186   
n=2,lam=50.0,c=1    1.0  50.0  2.0              4082.0       0.931346   
n=2,lam=50.0,c=25  25.0  50.0  2.0              2311.0       0.934959   
n=2,lam=50.0,c=50  50.0  50.0  2.0              2004.0       0.924119   
n=3,lam=1.0,c=1     1.0   1.0  3.0             56491.0       0.953930   
n=3,lam=1.0,c=25   25.0   1.0  3.0             13918.0       0.971996   
n=3,lam=1.0,c=50   50.0   1.0  3.0             10386.0       0.957543   
n=3,lam=25.0,c=1    1.0  25.0  3.0             56504.0       0.955736   
n=3,lam=25.0,c=25  25.0  25.0  3.0             13911.0       0.955736   
n=3,lam=25.0,c=50  50.0  25.0  3.0             10390.0       0.960253   
n=3,lam=50.0,c=1    1.0  50.0  3.0             56476.0       0.937669   
n=3,lam=50.0,c=25  25.0  50.0  3.0             13929.0       0.960253   
n=3,lam=50.0,c=50  50.0  50.0  3.0             10391.0       0.953930   

                   test_average  test_precision  test_recall  
n=1,lam=1.0,c=1        0.872551        0.881566     0.858040  
n=1,lam=1.0,c=25       0.876884        0.880161     0.876959  
n=1,lam=1.0,c=50       0.869021        0.871959     0.869701  
n=1,lam=25.0,c=1       0.855466        0.846593     0.865242  
n=1,lam=25.0,c=25      0.851823        0.854716     0.858837  
n=1,lam=25.0,c=50      0.853456        0.859170     0.847539  
n=1,lam=50.0,c=1       0.863020        0.862295     0.867685  
n=1,lam=50.0,c=25      0.841529        0.838411     0.833421  
n=1,lam=50.0,c=50      0.864366        0.864952     0.862743  
n=2,lam=1.0,c=1        0.951320        0.947365     0.953569  
n=2,lam=1.0,c=25       0.926925        0.918301     0.929322  
n=2,lam=1.0,c=50       0.937630        0.930895     0.939808  
n=2,lam=25.0,c=1       0.908013        0.901659     0.906391  
n=2,lam=25.0,c=25      0.935833        0.925546     0.943382  
n=2,lam=25.0,c=50      0.937539        0.932074     0.938358  
n=2,lam=50.0,c=1       0.923758        0.919261     0.920668  
n=2,lam=50.0,c=25      0.929445        0.928944     0.924432  
n=2,lam=50.0,c=50      0.916179        0.898025     0.926393  
n=3,lam=1.0,c=1        0.953133        0.953660     0.951809  
n=3,lam=1.0,c=25       0.971060        0.972992     0.968191  
n=3,lam=1.0,c=50       0.955980        0.958117     0.952281  
n=3,lam=25.0,c=1       0.956078        0.963331     0.949167  
n=3,lam=25.0,c=25      0.951829        0.956720     0.943030  
n=3,lam=25.0,c=50      0.961098        0.961340     0.961700  
n=3,lam=50.0,c=1       0.935771        0.954081     0.915564  
n=3,lam=50.0,c=25      0.961213        0.963647     0.959738  
n=3,lam=50.0,c=50      0.950535        0.944941     0.952734

In [147]:
#X_train = pd.read_csv("data/train_set_x.csv")['Text'].values
#Y_train = pd.read_csv("data/train_set_y.csv")['Category'].values
#X_test  = pd.read_csv("data/test_set_x.csv")['Text'].values
nbayest = NaiveBayesClassifier()
nbayest.set_params(n_gram=3,
                   multimap=True,
                   count_threshold=25,
                   use_uniform_prior=False,
                   laplace_smoothing=1.0)
nbayest.fit(X_train, Y_train)
pred = nbayest.predict(X_test)

output = pd.DataFrame({'Id': range(0, len(pred)), 'Category': pred})
output.to_csv("NaiveBayesClassifier_test_predictions.csv")


In [154]:
nbayest = NaiveBayesClassifier()
nbayest.set_params(n_gram=1,
                   multimap=True,
                   count_threshold=25,
                   use_uniform_prior=False,
                   laplace_smoothing=1.0)
nbayest.fit(X_train, Y_train)
pred = nbayest.predict(X_test)

output = pd.DataFrame({'Id': range(0, len(pred)), 'Category': pred})
output.to_csv("NaiveBayesClassifier_test_predictions_2.csv")

In [155]:
nbayest = NaiveBayesClassifier()
nbayest.set_params(n_gram=1,
                   multimap=True,
                   count_threshold=25,
                   use_uniform_prior=True,
                   laplace_smoothing=1.0)
nbayest.fit(X_train, Y_train)
pred = nbayest.predict(X_test)

output = pd.DataFrame({'Id': range(0, len(pred)), 'Category': pred})
output.to_csv("NaiveBayesClassifier_test_predictions_3.csv")